apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: cpu-stress-1
  namespace: test-argo
  labels:
    app: cpu-stress-1
spec:
  replicas: 1
  selector:
    app: cpu-stress-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cpu-stress-1
    spec:
      containers:
        - name: cpu-stress-1
          image: docker.io/containerstack/cpustress
          imagePullPolicy: Always
          ports:
          resources:
            requests:
              cpu: 60m
              memory: 128Mi
            limits:
              cpu: 500m
          args: ["--timeout", "86400s", "--cpu", "12"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
  triggers:
    - type: ConfigChange
  revisionHistoryLimit: 1
