apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-3
  namespace: test-argo
  labels:
    app: cpu-stress
    version: v1
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress-3
  template:
    metadata:
      labels:
        app: cpu-stress-3
        version: v1
    spec:
      automountServiceAccountToken: false
      containers:
      - name: cpu-stress-3-1
        image: docker.io/containerstack/cpustress
        imagePullPolicy: Always
        args: ["--timeout", "86400s", "--cpu", "1"]
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      - name: cpu-stress-3-2
        image: docker.io/containerstack/cpustress
        imagePullPolicy: Always
        args: ["--timeout", "86400s", "--cpu", "1"]
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
