apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
  name: hpa-cpustress-3
  namespace: test-argocd
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
    scaleUp:
      policies:
      - periodSeconds: 5
        type: Percent
        value: 1000
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 200
  metrics:
  - containerResource:
      container: cpu-stress-3-1
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: ContainerResource
  - containerResource:
      container: cpu-stress-3-2
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: ContainerResource
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-stress-3
