apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mysql
  namespace: test-argo
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
    db: mysql
spec:
  replicas: 1
  selector:
    db: mysql
    deployment: mysql
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 45
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        db: mysql
        deployment: mysql
    spec:
      containers:
        - name: mysql
          image: docker.io/mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_PASSWORD
              value: pass
            - name: MYSQL_USER
              value: user
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          resources:
            requests:
              cpu: 4000m
              memory: 5Gi
            limits:
              cpu: 10
              memory: 12Gi
  triggers:
    - type: ConfigChange
  revisionHistoryLimit: 3

